import type { ProjectDoc, TechDoc } from "@/lib/types";

export const seedProjects: Omit<ProjectDoc, "_id">[] = [
  {
    name: "SaniBlog",
    tagline: "همین وبلاگی که داری می‌خوانی؛ باغ دیجیتال شخصی",
    year: 2026,
    tech: ["Next.js", "React", "TypeScript", "MongoDB", "Tailwind CSS", "Motion"],
    url: null,
    highlight: "رندر سروری + گراف دانش + رادار تکنولوژی",
  },
  {
    name: "SaniShop",
    tagline: "فروشگاه کامل با سبد خرید واقعی و درگاه پرداخت",
    year: 2025,
    tech: ["Next.js", "PostgreSQL", "Prisma", "Redis", "Docker"],
    url: "https://youtube.com/@sanidev-web",
    highlight: "پردازش همزمان سفارش‌ها با صف Redis",
  },
  {
    name: "PulseBoard",
    tagline: "داشبورد تحلیلی زنده با نمودارهای لحظه‌ای",
    year: 2025,
    tech: ["React", "Node.js", "Socket.io", "MongoDB", "Docker"],
    url: "https://youtube.com/@sanidev-web",
    highlight: "استریم ۵ هزار رویداد در ثانیه روی WebSocket",
  },
  {
    name: "Weatherino",
    tagline: "اپ موبایل آب‌وهوا با انیمیشن‌های وابسته به وضعیت هوا",
    year: 2024,
    tech: ["React Native", "Expo", "TypeScript", "Skia"],
    url: "https://youtube.com/@sanidev-web",
    highlight: "انیمیشن ذرات باران روی Skia با ۶۰ فریم",
  },
  {
    name: "Folio3D",
    tagline: "پورتفولیوی سه‌بعدی تعاملی — پروژه‌ی محبوب کانال",
    year: 2024,
    tech: ["Three.js", "React", "GSAP", "Blender"],
    url: "https://youtube.com/@sanidev-web",
    highlight: "صحنه‌ی WebGL با نورپردازی بیک‌شده‌ی دستی",
  },
  {
    name: "TaskFlow",
    tagline: "مدیریت تسک تیمی با برد کانبان و آفلاین‌سیت",
    year: 2024,
    tech: ["MongoDB", "Express", "React", "Node.js", "Redux"],
    url: "https://youtube.com/@sanidev-web",
    highlight: "سینک آفلاین با IndexedDB و حل تداخل",
  },
  {
    name: "SaniBot",
    tagline: "بات تلگرام یادآور مطالعه با ۱۲ هزار کاربر",
    year: 2023,
    tech: ["Node.js", "Telegraf", "MongoDB"],
    url: "https://youtube.com/@sanidev-web",
    highlight: "زمان‌بندی فارسی هوشمند با کران‌جاب",
  },
];

export const seedTechs: Omit<TechDoc, "_id">[] = [
  { name: "Next.js", category: "framework", ring: "adopt", note: "فریم‌ورک اصلی کانال؛ از نسخه‌ی ۱۳ تا ۱۶" },
  { name: "React", category: "framework", ring: "adopt", note: "پایه‌ی همه‌ی پروژه‌های UI" },
  { name: "TypeScript", category: "framework", ring: "adopt", note: "بدون تایپ دیگر کد نمی‌زنم" },
  { name: "Node.js", category: "framework", ring: "adopt", note: "بک‌اند پیش‌فرض برای API و بات" },
  { name: "MongoDB", category: "data", ring: "adopt", note: "Aggregation Pipeline بهترین دوستم" },
  { name: "PostgreSQL", category: "data", ring: "adopt", note: "برای داده‌ی رابطه‌ای و تراکنش‌های سنگین" },
  { name: "Tailwind CSS", category: "style", ring: "adopt", note: "از نسخه‌ی ۴ دیگر CSS-first است" },
  { name: "Docker", category: "tool", ring: "adopt", note: "همه‌ی پروژه‌ها کانتینری دیپلوی می‌شوند" },
  { name: "Motion", category: "style", ring: "trial", note: "فیزیک و gesture برای ری‌اکت" },
  { name: "tRPC", category: "framework", ring: "trial", note: "تایپ‌سیف end-to-end بدون codegen" },
  { name: "Expo", category: "framework", ring: "trial", note: "موبایل بدون دردسر نیتیو" },
  { name: "Socket.io", category: "data", ring: "trial", note: "ریل‌تایم سریع برای داشبوردها" },
  { name: "Redis", category: "data", ring: "trial", note: "کش و صف، هنوز دارم عمیق‌ترش می‌کنم" },
  { name: "Prisma", category: "data", ring: "trial", note: "DX عالی برای SQL" },
  { name: "Three.js", category: "style", ring: "assess", note: "سه‌بعدی وب؛ سنگین ولی وسوسه‌انگیز" },
  { name: "Bun", category: "tool", ring: "assess", note: "ران‌تایم سریع؛ هنوز برای پروداکشن مطمئن نیستم" },
  { name: "Astro", category: "framework", ring: "assess", note: "برای سایت‌های محتوایی گزینه‌ی جذابی است" },
  { name: "GSAP", category: "style", ring: "assess", note: "برای انیمیشن‌های timeline پیچیده" },
  { name: "Redux", category: "data", ring: "hold", note: "دیگر فقط برای پروژه‌های لگسی" },
  { name: "Create React App", category: "tool", ring: "hold", note: "به‌خاطر گذشته‌ها، با احترام بازنشسته شد" },
  { name: "jQuery", category: "framework", ring: "hold", note: "اولین عشق وب‌ام؛ دورانش گذشته" },
];
